name: UI tests Product V2
on:
  pull_request:
    paths:
      - .github/workflows/sanity-productV2.yml
      - tests/UI/campaigns/productV2/**
      - admin-dev/themes/new-theme/js/pages/product/**
      - src/PrestaShopBundle/Form/Admin/Sell/Product/**
      - src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/**
      - src/Core/Domain/Product/**
      - src/Adapter/Product/**
      - src/PrestaShopBundle/Resources/views/Admin/Sell/Catalog/Product/**

permissions:
  contents: read   #   to fetch code (actions/checkout)

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  TEST_CAMPAIGN: 'sanity:productV2:fast-fail'

jobs:

  sanity-product:
    runs-on: ubuntu-latest
    name: Sanity Product V2
    strategy:
      matrix:
        php: [ '7.2', '7.3', '7.4', '8.0', '8.1' ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup Environment
        timeout-minutes: 15
        uses: ./.github/actions/setup-env
        with:
          PHP_VERSION: ${{ matrix.php }}
          INSTALL_AUTO: 'true'

      - name: Run Tests
        uses: ./.github/actions/ui-test
        with:
          TEST_CAMPAIGN: ${{ env.TEST_CAMPAIGN }}

      - name: Upload Screenshots and logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: sanity-productV2-${{ matrix.php }}
          path: ./tests/UI/screenshots/
